image: openjdk:11

variables:
  DB_IP : ec2-52-209-246-87.eu-west-1.compute.amazonaws.com
  DB_PORT : 5432
  DB_USER : ahztgqmjarqktn
  DB_PASSWORD : 5eaba1ff094dc957efdda479b7ac7219885fab7a20c63cb05617acd6844a820d
  DB_NAME : d45go7pldb1o92

stages:
  - lint
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

test:
  stage: test
  script:
    - ./gradlew test

lint:
  stage: lint
  script:
    - ./gradlew checkStyleMain

deploy:
  stage: deploy
  only : 
    - main
  image : ruby:2.4
  script:
    - apt-get update
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds-assignment-ga --api-key=$HEROKU_API_KEY
